spring.application.name=api
spring.datasource.url=jdbc:mysql://16.171.122.165:3306/revenda_segura?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=app_revenda
spring.datasource.password=TuPasswordSegura123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
stripe.webhook.secret=  whsec_b4d1430b0ac16dd5b93c80a72f74235fdc10208871fad87b7a652fdeebed68f3
stripe.api.key=sk_test_51TOg6YH3agIzzdNNrngNR8jrgCrXFVkSZPQUDSeOjiXV7iUHfernhkgyAV9xQTPYQ03dIvi76ApU561x5YFTqByw001jgqLbAL

aws.s3.bucket.name=revenda-segura-media-itic
aws.region=eu-north-1
aws.access.key.id=AKIAU2ROJMCF6ADOZWOZ
aws.secret.access.key=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